coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 5%

flags:
  android-unit-tests:
    paths:
      - app/src/main/
      - shared/src/
    carryforward: true
  android-instrumented-tests:
    paths:
      - app/src/main/
    carryforward: true
  shared-tests:
    paths:
      - shared/src/
    carryforward: true
  ios-tests:
    paths:
      - iosApp/UkuleleCompanion/
    carryforward: true

comment:
  layout: "reach,diff,flags,components"
  behavior: default
  require_changes: false
